# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
relative_permalinks: false

# Setup
title:              Connor Goldberg
tagline:            Electrical Engineer
description:        Contents
url:                http://connorgoldberg.com
baseurl:            ""
urlimg:             /static/
markdown:           kramdown
paginate:           3
paginate_path:      /blog/page:num
permalink:          /blog/:year/:month/:day/:title/
excerpt_separator:  <!--more-->
default_bg:         sitebg.jpg
default_logo:       sitelogo.png
safe:               false
future:             true

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compose
  - bundler
  - kramdown
  - font-awesome-sass
  - jemoji
  - rouge

exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant", "_site", "_static", "fabfile.*"]

# Owner/author information
# Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
owner:
  name:         Connor Goldberg
  avatar:       prof.jpg
  email:        connor@connorgoldberg.com
  description:  Electrical Engineering
 
  twitter:        connorjan94
  facebook:       ConnorJan
  github:         https://github.com/connorjan
  repo:           https://github.com/connorjan/connorjan.github.io
  linkedin:       https://www.linkedin.com/in/connorgoldberg 

# Show a scroll progress bar on the configured pages
# This can be overridden on a per-page basis by the pages frontmatter like:
# progressbar:
#   color: "#123456"
progressbar:
  configs: 
    - layout: post
      # color: black

header:
    # Header icons:
    # Check out this link to view the classes: http://fontawesome.io/cheatsheet/
    icons:
        - title: About
          url: /about/
          class: fa fa-user
        - title: Contact
          url: /contact/
          class: fa fa-envelope
        - title: Resume
          url: /resume/
          class: fa fa-file-text

# footer links are located in /data/socialmedia.yml

# sidebar links:
# These will follow any pages that are of type:page
# For external links add external: true

links:
  - title:  Home
    url:    /
  - title:  About
    url:    /about/
  - title:  Projects
    url:    /projects/
  - title:  Blog
    url:    /blog/
  - title:  Contact
    url:    /contact/
  - title:  Resume
    url:    /resume/

#sidebarfooter: "Add something here!"

# Version is shown as the last item of the sidebar. Comment out to remove
version: 2.0

showcopyright: 
    sidebar: true
    footer: true

cssoverrides:
   - file: /public/css/header.css

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
#twitter_widget_id: xyz123abc

# Add disqus username for Disqus comment board:
#disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc
